### ISSUE TITLE
Refactoring `get_stat_counters`

### ISSUE THREAD

**Issue by maximecb** [Shopify/yjit#107]
Noah would like to refactor `get_stat_counters` so it exposes more stats to Ruby code, which he is going to use for the `yjit-metrics` project. The main problem we have is that the exit reasons are mixed with many other counters. I agree with the general idea that our stats/counters probably should be better organized. My main concern right now is that the C code is a bit messy, and I would like the C code to get cleaner, not messier.

I think it would make sense having `get_stat_counters` return a struct which has different fields in it. AFAIK, semantically all the values we have so are are "counters". They're all integer values that get incremented. So I would avoid referring to some of them as counters and others not.

AFAIK exit_op_count are just "toplevel" counts of how many times we exit for a given instruction. Whereas the yjit_runtime_counters are assorted counters, which include a breakdown of "exit reasons" for the `exit_op_count`. 

It would be kind of nice if the C code could separate the exit reason counters into their own hash. That seems cleaner, though that could be annoying to do in C because we're using the same convenient mechanism for `bindings_set` and for exit reasons right now.

The simplest thing to do on the C side might be to get rid of the `exit_op_count`, and prefix all exit counters with `exit_`. So then, the toplevel exit counter for `send` would be `exit_send`. Then the exit reasons would be things like:

- `exit_send_callsite_not_simple`
- `exit_send_kw_splat`
- `exit_send_ic_empty`
- ...

The C code could probably handle, based on the counter name, separating the exit counters into different hashes in the struct returned by `get_stat_counters`. I think it would make sense to include things like the inlined/outlined machine code size in these stats/counters returned by `get_stat_counters` and have all the stats printing be done in Rubyland, as opposed to the current scheme where we do some printing in Ruby and some in C.

**Comment by noahgibbs** [comment]
PR to convert vm_insns_count and rb_compiled_iseq_count to counters rather than freestanding variables: https://github.com/Shopify/yjit/pull/109

**Comment by noahgibbs** [comment]
In the meeting you talked about wanting to convert some of the stuff done in C to Ruby. It looks like right now some of the end-of-process report is printed from Ruby and some from C. Specifically, in yjit_iface.c a method at_exit_print_stats is called on exit, which calls the Ruby method YJIT._print_stats(). It displays everything in the exit report from "***YJIT: Printing runtime counters from yjit.rb***" to "opt_aref exit reasons:" and the counter value(s).

However, there is also a C function print_yjit_stats which appears to run because it has __attribute__((destructor)), which is a GCC compile-time method of registering an at-exit function ("https://gcc.gnu.org/onlinedocs/gcc-4.7.0/gcc/Function-Attributes.html"). It appears to print everything from "compiled_iseq_count" to the end of the stats report from C instead of Ruby.

I'll plan to convert the C code to Ruby after I expose the necessary values via YJIT.runtime_stats().

**Comment by maximecb** [comment]
> I don't think we collect centralised "can't compile" reasons, but a lot of our counters are for that, too, e.g send_callsite_not_simple, bend_bmethod, send_undef_method, send_iseq_tailcall.

Let's hold off on that because Alan's work to convert YJIT to use call threading will change the meaning of these things a bit. It will add a different kind of fallback that doesn't exit to the interpreter.

> I think we can move those two raw integers into counters. I don't think we want to move all of exit_op_count into the existing yjit_runtime_counters mechanism.

Makes sense 👍 

> It would be possible to include only nonzero exit_op_count counters to the hash. I'm a bit leery about that, but it would save space.

If you mean saving memory, that's not a concern for this use case since we're talking kilobytes.

Removing unused counters is a good idea. Maybe we can have a hash that corresponds to `exit_op_count` and one for `yjit_runtime_counters` and package both of those into a stats struct?

**Comment by noahgibbs** [comment]
> Let's hold off on that because Alan's work to convert YJIT to use call threading will change the meaning of these things a bit. It will add a different kind of fallback that doesn't exit to the interpreter.

Makes sense. I wasn't planning to separate out the counters into different categories in YJIT. Instead, I'm making lists of what the different counters are used for in yjit-metrics so that I can give those reports after the fact. Simple lists of counter names in Ruby should be easy enough to change later if we want to.

> Removing unused counters is a good idea. Maybe we can have a hash that corresponds to exit_op_count and one for yjit_runtime_counters and package both of those into a stats struct returned by get_stat_counters ?

Certainly. My current plan is to insert the exit_op_count entries into the same hash, but prefix its key names with "exit_". So the entries would look like:

~~~
{
  compiled_iseq_count: 93,
  vm_insns_count: 95328,
  exit_getglobal: 700,
  exit_leave: 19697,
}  
~~~
