### ISSUE TITLE
Avoid discarding type information at every call

### ISSUE THREAD

**Issue by maximecb** [Shopify/yjit#304]
At the moment, we discard type information at every call, whether it be a call to a C function or another iseq, because it could be that a bindings environment or a closure could access the locals later. This is inefficient because it means we lose potentially useful type information we could use for further optimizations down the road.

We've gathered some data and seen that in practice, although bindings is sometimes used in production, it's never used to write to the locals of a caller. This is something that's very rare.

I think it would be worth it to think about how we can avoid dropping all type information at every call. We could potentially have a mode where YJIT will throw an exception if someone tries to use bindings to write to the locals of a caller, or we could exit and discard all compiled code if/when someone does. Potentially, we could reuse the same mechanism that we use for `TracePoint` here.

Alan suggests that we also have to account for closures potentially capturing and modifying local variables. It should be possible to tell which functions have no closures based on their syntax. In fact, it should be possible to tell which specific local variables are captured by closures (if any).

@XrXr @kddnewton @noahgibbs @tenderlove

**Comment by noahgibbs** [comment]
As you say, we're seeing very few writes through bindings, even on very large apps. Alan points out that writes via closures are much more common, and we don't currently track those. It *is* possible for that to mess up our type information -- though really common cases like writing an element into an array are currently fine because we don't track the things it would mess up :-)

C extensions also have massive ability to mess us up here -- they can alter local variables and in many cases there's nothing we can do to hook or track that. But C extensions tend to avoid that where they can, and/or mark themselves as non-prod when they do problematic things (e.g. https://rubygems.org/gems/binding_of_caller or similar debugging gems like Pry). It's *probably* fine for us to sometimes have incorrect behaviour when a C extension reaches in, binding-style, and messes with local variables in a non-Ruby-API way.

Right now I suspect closures work fine because we don't track most of the information they can change. For instance, once we add object shapes, and thus track frozen objects, it becomes a problem for a method to call "closed_var.freeze". Right now it's fine because we don't do any compile-time tracking of frozen status. And you can't change a variable's type at runtime. Similarly, if we started tracking "Array of Integer" in the type information, suddenly writing an array element through a closure becomes suspect - how do you make sure they haven't added a nil? But right now we don't care, so it doesn't mess us up.

So in practice, a lot of this issue is probably about reading and understanding how CRuby implements closures to find out what we can and can't guarantee going forward. Bindings seem to be a practical non-issue in most cases. They're just not used that often.

**Comment by noahgibbs** [comment]
For what C extensions *can* do, the answer is of course "anything." I don't know how common bad behaviour is. But there's no central registry of C extensions or any way to keep people from doing what they feel like - you can just build one as part of any app or gem, for instance. So there's probably a long tail of rare weird bad behaviour out there -- which we can mostly ignore, so that's better than it could be.

I don't know if there's a common list of "don't do this" anywhere for writing C extensions. Last time I checked, it's mostly extremely loose enforcement, if any :-/

On the plus side, I would expect writing to local variables to be fairly rare. Much more frequent is a C extension making a Ruby structure and returning it, which shouldn't normally mess us up.

I should probably look through things like Pry that are common and read/write locals. Though the ones I currently know of are all "don't have to support it in production" software like debuggers.

If there's something that's already rarely done and a bad idea, we can probably talk to the people who maintain the 2-5 common gems that use it (or however many) individually and get most of them updated. Shopify already pushes for these kinds of changes with a lot of gems in other ways (esp. fixes, updates.) But it doesn't always work (e.g. grpc doesn't want to take our patches, or basically anybody else's.)

So yeah, 100% agree that we need to see what CRuby currently does, make a list of what we need from C extension authors and then figure out how much trouble we're looking at to make it work that way.

At a quick glance, kinda looks like in compile.c, CRuby is capturing the relevant scopes while creating ISEQs. But that's just a quick glance -- plenty of room for me to miss something major.

**Comment by maximecb** [comment]
> I don't know if there's a common list of "don't do this" anywhere for writing C extensions. Last time I checked, it's mostly extremely loose enforcement, if any :-/

There's definitely things that are not recommended / not sanctioned for C extensions to do. We also have the ability to talk with the Ruby core developers and push for certain changes and guarantees.

If there are C extensions reading/writing the stack directly without using bindings, I'd like to see some code samples to see what they are doing and how.

**Comment by eregon** [comment]
There is notably `rb_binding_new()`, that I hear captures the binding of the Ruby frame right above it, and from that Binding object it's of course possible to write, etc, at any time later.
There are probably a few more C API which access the caller Ruby frame, I think @XrXr knows well about those.
There is also the debug inspector C API, which can get bindings of all callers, but that's supposed to be a "debug-only" API.

I'm also thinking to `rb_block_proc()` which gets the block passed to a C extension method. And there is Proc#binding. So any local variable outside of a block is potentially read/written through Proc#binding + Binding#eval/local_variable_set.
There are a few discussions about this kind of things on https://bugs.ruby-lang.org/, the most recent are https://bugs.ruby-lang.org/issues/18461 and https://bugs.ruby-lang.org/issues/18780.

I'd be in favor of deprecating Proc#binding because there doesn't to be much of a legitimate use case for it. But I don't think that on its own changes much, since `Kernel#binding`/`rb_binding_new()`/*eval are as powerful, and `Kernel#binding` and `*eval` can be aliased so they can't be found statically.

My general opinion on this is to ensure a local variable is not written in Ruby, the only sure way is to compile and inline the call and have the compiler prove it is not written (what TruffleRuby does). Otherwise it might be written, and as an example I don't think it's OK to have incorrect behavior in a REPL based on such an optimization.

**Comment by eregon** [comment]
> Recently there's been a change so Kernel#binding can't be called from a non-Ruby frame: https://github.com/ruby/ruby/pull/5767

Indeed, although that doesn't affect rb_binding_new(), https://gist.github.com/eregon/fc779aca9c37595ffde7473b424769c7 prints:
```
[:main]
[:my_method_var]
```

(I actually thought there was no `rb_binding_new()` until recently, it seems it was added in 2.7).

> Incremental improvements to make the life of Ruby implementers easier and make Ruby a slightly simpler language.

I certainly agree. Sometimes it's accepted and sometimes it's not, often for worries about compatibility.

**Comment by maximecb** [comment]
@jeremyevans should `rb_binding_new` also raise a RuntimeError if called from a non-ruby frame, just like `Kernel#binding` does (as per https://github.com/ruby/ruby/pull/5767) ?

This would be helpful for YJIT.

**Comment by maximecb** [comment]
> use the TracePoint global invalidation thing when we detect a binding being created for a frame without a block

We might be able to get away with not invalidating until someone actually uses binding to write to a frame (most bindings only read). That would make this kind of invalidation much less likely.

I think limiting ourself to methods that have no blocks is a good start. It would be good if we could also handle methods with blocks eventually.

**Comment by eregon** [comment]
> We might be able to get away with not invalidating until someone actually uses binding to write to a frame (most bindings only read).

Is there a reliable way to detect that? It's not only Binding#local_variable_set but also Binding#eval which can assign outer variables (and indirectly e.g. by Binding#eval creating a block which assigns the variable and is caller later on).

**Comment by jeremyevans** [comment]
> @jeremyevans should `rb_binding_new` also raise a RuntimeError if called from a non-ruby frame, just like `Kernel#binding` does (as per [ruby/ruby#5767](https://github.com/ruby/ruby/pull/5767)) ?

`Kernel#binding` is basically calling a C method (`rb_f_binding`), then calling `rb_binding_new` in that C frame. It should already raise if the directly preceding frame is a non-Ruby frame, but the current frame when calling `rb_binding_new` C function should always be a C frame. So any C method should be able to call `rb_binding_new` and get a binding for the Ruby frame that called the C method.  However, you cannot have a C method that calls a C method that calls `rb_binding_new`.

If we wanted to prevent the ability to get a binding from a C method completely, we would have to move the `rb_binding_new` implementation into `rb_f_binding` (a static method), then remove `rb_binding_new`.  I'm not against that, but it's something that would have to be discussed at a developer meeting.

**Comment by noahgibbs** [comment]
I put together an uncommitted code change to throw away less type information with a command-line parameter (https://github.com/Shopify/ruby/commit/4f93bf3f88e26f29f1da358bb178eb38fc14538b). Unfortunately, so far it appears to be either no speed change or slightly *slower* for large benchmarks, apparent due to more side exits. I can think of some possible reasons that might be, but I don't have compelling evidence of exactly what's happening as yet.

**Comment by maximecb** [comment]
> It sounds like for now we're tabling this, since propagating type information farther doesn't improve performance (yet?)

I would have liked to see how it affects perf on an idealized microbenchmark, for example a while loop with an integer index and one bytecode that does a Cfunc send. Just for validation.

> Right now our use of type info to deal with polymorphism at a call site is extremely basic, and I think that's biting us here. As it becomes less basic, maybe propagating type info farther will be more useful.

What do you mean more specifically by extremely basic use of type info to deal with polymorphism? (not taking offence to the statement, just asking for specifics).

**Comment by noahgibbs** [comment]
Right now, we ignore the types of operands passed through until the call count for a particular method reaches our threshold (10, usually) and then assume that either it will always be the type from the 10th call, or assume it will be one of a small number of types (jit_chain_guard) ordered by when we encountered them. That means that if we hit the "wrong" type first, it can cause a lot of side exits, and if there are multiple types for an arg we may not realise that - e.g. sometimes we just side exit a lot, which can be quite slow.

As an extreme in the other direction, TruffleRuby does a huge amount of checking how often is sees different types in different argument positions, etc, and makes little decision trees to get to the right sub-method. It watches for when its assumptions are violated and recompiles methods with the new profiling information. I'm not saying we want all that -- I think we benefit from being simple. But I'm saying there's a lot of room for more complexity in that direction, even if we do far less than Truffle.

**Comment by maximecb** [comment]
I don't really want to get into an in-depth discussion of that in this thread but we already do generate multiple versions of methods, and I believe the way BBV handles type information works out well in practice. For instance, AFAIK, we get very few side exits because we exceed the chain depth (based on our profiling counters). The overwhelming majority of the side-exits that we do get are due to unsupported instructions and unimplemented code paths.

Before we table this, can you run the while loop experiment? The reason I'm asking about the while loop microbenchmark is so that we can get a baseline to measure effect size. If we create an idealized microbenchmark of a loop with one small call (which we know will drop the type information) and we measure with and without (in a release config), we can measure how big the delta is. If it turns out to be really tiny (which I suspect it will be), then we know our assumption is right.

There's a lot more we could do in terms of data-driven optimization but it will have to wait until next year. Jimmy Miller built a nice visualization of the code we generate. We could do something like that with methods from SFR or railsbench so we can actually "see" the code being generated.
