### ISSUE TITLE
Ruby stack ABI compatibility

### ISSUE THREAD

**Issue by javierhonduco** [Shopify/yjit#305]
👋🏻 Hi folks, I am developing a Ruby profiler, [rbperf](https://github.com/javierhonduco/rbperf/), that works by reading the Ruby process' memory from a [BPF](https://ebpf.io/) program implemented [here](https://github.com/javierhonduco/rbperf/blob/main/src/bpf/rbperf.bpf.c). It relies on Ruby's ABI to be able to walk Ruby's stack frames to understand the sizes of structs, offsets of some fields we want to read, etc.

After some brief testing, it seems that it works well with YJIT enabled! 

Was curious what are your thoughts on maintaining the current Ruby frame system or if you had other plans such as shadow-frames or something similar in case you won't use them in the future, so debuggers and similar tools such as rbperf can work

Thanks!

**Comment by javierhonduco** [comment]
Thanks, @maximecb! If possible I want to make rbperf work for YJIT users, so looking forward to @XrXr's talk!

**Comment by XrXr** [comment]
It should be possible to retrieve a backtrace even after YJIT makes optimizations because YJIT itself needs to be ready to do so. The code could call `Kernel#caller` at any time from a method defined in C opaque to YJIT and YJIT needs to be ready to handle that, for example. It's not necessarily going to be easy to do it with eBPF facilities, but it should be possible in principle.

By the way, thanks for putting together the eBPF program! I've found eBPF to be quite indispensable for certain issues in the past so I'm glad Ruby users have the option to use it.

**Comment by javierhonduco** [comment]
@XrXr that makes a lot of sense, thanks for the explanation! Sounds very hard to have to account for all these cases.

> By the way, thanks for putting together the eBPF program! I've found eBPF to be quite indispensable for certain issues in the past so I'm glad Ruby users have the option to use it.

Indeed, BPF's super handy while debugging complex issues. If you ever give rbperf a whirl, happy to hear any feedback you might have!
